export const userStatusMap = {
    ON_VACATION: "🏖️ On vacation",
    AT_WORK: "💼 At work",
    IN_MEETING: "📅 In a meeting",
    AVAILABLE: "✅ Available",
    AWAY: "🟡 Away",
    BUSY: "🔴 Busy",
    DO_NOT_DISTURB: "🚫 Do not disturb",
    AT_GYM: "🏋️‍♂️ At the gym",
    AT_HOME: "🏠 At home",
    TRAVELING: "✈️ Traveling",
    SLEEPING: "😴 Sleeping",
    IN_CLASS: "🏫 In class",
    STUDYING: "📚 Studying",
    AT_COFFEE_SHOP: "☕ At a coffee shop",
    OUT_FOR_LUNCH: "🍽️ Out for lunch",
    OFFLINE: "📴 Offline",
    AT_DOCTOR: "🩺 At the doctor's appointment",
    ON_CALL: "📞 On a call",
    IN_CONFERENCE: "🎤 In a conference",
    TAKING_BREAK: "🛋️ Taking a break",
    ON_TRIP: "🧳 On a trip",
    AT_PARTY: "🎉 At a party",
    IN_TRANSIT: "🚗 In transit",
    ON_HOLIDAY: "🌴 On holiday",
    WORKING_REMOTELY: "🏡 Working remotely",
};
